project_id = "dmvbwyfzueywuwxkjuuy"

[functions.monitor-heartbeat]
verify_jwt = false

[functions.get-turn-credentials]
verify_jwt = false

[functions.register-device]
verify_jwt = false

[functions.get-devices]
verify_jwt = false

[functions.update-device]
verify_jwt = false
